---
title: "Module 5 Your Turns"
author: "Pete Talbert"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)

tuition_cost <- read_csv("data/tuition_cost.csv")

diversity_school <- read_csv("data/diversity_school.csv")

salary_potential <- read_csv("data/salary_potential.csv")


```

```{r, your turn instructions, include=FALSE}
# Let's practice using pivot_longer to reshape our data! -----------------------------------
# 1) FIRST, CREATE A NEW DATAFRAME WHERE THE COST DATA IS PIVOTED LONGER. SAVE IT AS tuition_cost_long.
# 2) TAKE THAT NEW DATAFRAME, AND GROUP BY THE NEWLY CREATED COLUMN, cost_type. FIND THE MEDIAN cost ACROSS THE ENTIRE DATASET BY cost_type.
#    HOW MUCH MORE IS THE MEDIAN in_state_tuition THAN THE MEDIAN out_of_state_tuition? WRITE A QUICK SENTENCE BELOW #2 GIVING YOUR RESULTS.
# 3) WHY IS THE COST FOR THE room_and_board COST TYPE NA? USE FILTER APPROPRIATELY TO GET A NON-NA VALUE FOR room_and_board.
```

# 1)

```{r}
tuition_cost_long <- tuition_cost %>% 
  pivot_longer(cols = c(room_and_board, in_state_tuition, in_state_total, out_of_state_tuition, out_of_state_total), # WHICH COLUMNS GO HERE?
               names_to = "cost_type", 
               values_to = "cost")
```

# 2)

```{r}
tuition_cost_long %>% 
  group_by(cost_type) %>% 
  summarize(median_cost = median(cost))
```

The median out-of-state tuition is around $7,400 more than the median in-state tuition.

# 3)

```{r}
# this will filter out all rows that have NA costs.
tuition_cost_long %>% 
  filter(!is.na(cost)) %>% 
  group_by(cost_type) %>% 
  summarize(median_cost = median(cost))

# this will do the same thing in this instance (by using the na.rm optional argument in median()). But be aware this may be a better option than filter(!is.na(column_name))
# because if we were summarizing different columns, we would filter out rows we may want for different summaries.
tuition_cost_long %>% 
  group_by(cost_type) %>% 
  summarize(median_cost = median(cost, na.rm = TRUE))

# Here's an example where this would return different results:
# A) This removes ALL schools that have NA room_and_board; this changes the in_state_tuition.
tuition_cost %>% 
  filter(!is.na(room_and_board)) %>% 
  summarize(median_room_and_board = median(room_and_board),
            median_in_state_tuition = median(in_state_tuition))

# B) This still computes in_state_tuition from all schools.
tuition_cost %>% 
  summarize(median_room_and_board = median(room_and_board, na.rm = TRUE),
            median_in_state_tuition = median(in_state_tuition))
```
