---
title: "The Office IMDB Ratings"
author: "Pete Talbert"
date: "8/20/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)

tuition_cost <- read_csv("data/tuition_cost.csv")

diversity_school <- read_csv("data/diversity_school.csv")

salary_potential <- read_csv("data/salary_potential.csv")


```

```{r, your turn instructions, include=FALSE}
# Let's practice using inner_join() to combine datasets together! -----------------------------------
# 1) 
```

# 1)

```{r}
diversity_school_total <- diversity_school %>% 
  distinct(name, total_enrollment, state)
```

```{r}
tuition_cost %>% 
  inner_join(diversity_school_total, by = "state")

# what just happened?
```

```{r}
tuition_diversity_joined <- tuition_cost %>% 
  inner_join(diversity_school_total, by = c("state", "name"))

#Cool!
```

```{r}
tuition_diversity_joined %>% 
  ggplot(aes(x = out_of_state_tuition, y = total_enrollment)) +
  geom_point()

# Any relationship?
```











