---
title: "Module 5 Your Turns"
author: "Pete Talbert"
date: "8/20/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)

tuition_cost <- read_csv("data/tuition_cost.csv")

diversity_school <- read_csv("data/diversity_school.csv")

salary_potential <- read_csv("data/salary_potential.csv")


```

```{r, your turn instructions, include=FALSE}
# Let's practice using inner_join() to combine datasets together! -----------------------------------
# 1) IN ORDER TO GET A DISTINCT LIST OF COLLEGES WITH THEIR TOTAL ENROLLMENT, USE A count() ON diversity_school WITH THE COLUMNS name, total_enrollment, AND state.
#    SAVE THAT AS A NEW DATAFRAME.
# 2) NOW JOIN THIS NEW DATAFRAME TO tuition_cost BY state. HOW MANY ROWS DID IT RETURN? WHY?
# 3) NOW JOIN THE NEW DATAFRAME TO tuition_cost BY state AND name. HOW MANY ROWS DID IT RETURN? WHY? SAVE THIS JOINED DATAFRAME AS WELL
# 4) LASTLY, USE YOUR SAVED, JOINED DATAFRAME TO SEE IF THERE IS A RELATIONSHIP BETWEEN out_of_state_tuition AND total_enrollment. HINT: MAKE A SCATTERPLOT.
```

# 1)

```{r}
diversity_school_total <- diversity_school %>% 
  count(___, ___, ___)
```

We'll talk about the `distinct()` function in module 6, but for now, a way to get a distinct list of universities from `diversity_school` is just to get a count of the distinct columns we want.

# 2)

```{r}
tuition_cost %>% 
  inner_join(___, by = "___")

```

## What just happened?



# 3)

```{r}
tuition_diversity_joined <- tuition_cost %>% 
  inner_join(___, by = c("___", "___"))

```

## What just happened?



# 4)

```{r}
tuition_diversity_joined %>% 
  ggplot(aes()) +
  geom____()

```










