---
title: "The Office IMDB Ratings"
author: "Pete Talbert"
date: "8/20/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)

tuition_cost <- read_csv("data/tuition_cost.csv")

diversity_school <- read_csv("data/diversity_school.csv")

salary_potential <- read_csv("data/salary_potential.csv")


```

```{r, your turn instructions, include=FALSE}
# Let's practice using group_by() with window functions! -----------------------------------
# 1) 
```

```{r}
diversity_school_total <- diversity_school %>% 
  distinct(name, total_enrollment, state)
```


```{r}
diversity_school_total %>% 
  mutate(enrollment_rank = min_rank(desc(total_enrollment)))
```

```{r}
diversity_school_total %>% 
  group_by(state) %>% 
  mutate(enrollment_rank = min_rank(desc(total_enrollment)))
```


```{r}
diversity_school_total %>% 
  group_by(state) %>% 
  mutate(enrollment_rank = min_rank(desc(total_enrollment))) %>% 
  filter(enrollment_rank == 1)
```

What are MN, WI, and IA's top enrollment schools? Is it who you thought?
