---
title: "Module 5 Your Turns"
author: "Pete Talbert"
date: "8/20/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)

tuition_cost <- read_csv("data/tuition_cost.csv")

diversity_school <- read_csv("data/diversity_school.csv")

salary_potential <- read_csv("data/salary_potential.csv")


```

```{r, your turn instructions, include=FALSE}
# Let's practice using group_by() with window functions! -----------------------------------
# 1) WE CAN USE group_by() WITH mutate() IN LOTS OF DIFFERENT WAYS. LET'S START BY GROUPING BY state, AND RATHER THAN USING summarize(), USE mutate()
#    USE mutate() TO CREATE A NEW COLUMN THAT IS THE mean() OF out_of_state_tuition. ARRANGE BY state AND name. WHAT IS RETURNED? SAVE IT AS A NEW DATAFRAME.
# 2) NOW THAT WE HAVE THE avg_out_of_state_tuition FOR EACH ROW, WE COULD CALCULATE INDIVIDUAL SCHOOLS' DISTANCE FROM THE MEAN.
#    MAKE A NEW mutate() THAT IS THE DIFFERENCE BETWEEN out_of_state_tuition AND avg_out_of_state_tuition.
# 3) WE COULD FIND "TYPICAL" SCHOOLS BY STATE BY JUST FILTERING THIS NEW COLUMN. FILTER IT BY ABOVE OR BELOW THE MEAN BY 1000. 
#    WHAT ARE THE AVERAGE-PRICED SCHOOLS IN MINNESOTA?
```

# 1)

```{r}
tuition_cost_new <- tuition_cost %>% 
  group_by(___) %>% 
  mutate(___ = mean(___)) %>% 
  arrange(___, ___) %>% 
  ungroup() # always a good idea to ungroup() to ensure the data ungrouped when we don't want it to be for future work/transformations.
```

## What just happened?



# 2)

```{r}
tuition_cost_new %>% 
  mutate(___ = ___ - ___)
```

# 3)

```{r}
tuition_cost_new %>% 
  mutate(out_of_state_diff = out_of_state_tuition - avg_out_of_state_tuition) %>% 
  filter(out_of_state_diff ___ & out_of_state_diff ___)
```

